Dr patterns april
hmrc/design-system pull request #380
Opened 2022-04-05 14:38 UTC by klaudiarybicka

Changed the titles in question pages from xl to l

2022-04-05 16:22 UTC, Louisehmrc approved these changes

2022-04-07 08:32 UTC, Louisehmrc approved these changes

2022-04-07 09:44 UTC, Jon-Rowe-HMRC requested changes
All looks fine, except the headings are still showing as XL on http://localhost:3000/hmrc-design-patterns/page-heading/ for me despite the nunjucks change.

2022-04-07 09:46 UTC, klaudiarybicka commented
> All looks fine, except the headings are still showing as XL on http://localhost:3000/hmrc-design-patterns/page-heading/ for me despite the nunjucks change.

They are displaying as L to me, even after terminating the process and opening in the terminal again

2022-04-07 09:49 UTC, Jon-Rowe-HMRC commented
Hmm, weird I just cleared my caches etc and still XL in the HTML tab, L in the nunjucks tab.

Just go ahead and publish and I'll have a look at the published version.

2022-04-07 10:06 UTC, merged