NOJIRA: Updated hmrc-frontend and govuk-frontend versions to latest
hmrc/design-system pull request #822
Opened 2024-03-13 15:22 UTC by JoPintoPaul

2024-03-13 15:24 UTC, kyle-bowden approved these changes

2024-03-13 15:27 UTC, oscarduignan requested changes
does it still build ok? This path looks like it wouldn't work anymore

https://github.com/hmrc/design-system/blob/3a07f23a4644c05f01c432b159656fe9751a8d93/application/scss/hmrc-design-system.scss#L4

2024-03-13 15:30 UTC, oscarduignan commented
this one might be a bit bigger than a version bump - this was the revert of the changes that Tim did previously https://github.com/hmrc/design-system/pull/801/files#diff-6bb79e8fb5ac3928895b2778881b2e403ea3023cf689461702d47cb954198f43 (the original PR seems to have some extra commits in it so viewing it this way is backwards but bit clearer maybe)

2024-03-14 11:43 UTC, Jon-Rowe-HMRC approved these changes
No issue from me, but Tim will have a more informed view

2024-03-18 09:45 UTC, timsb approved these changes

2024-03-18 09:56 UTC, merged