Get started
hmrc/design-system pull request #858
Opened 2024-07-30 14:17 UTC by JackHMRC

2024-07-30 14:47 UTC, Jon-Rowe-HMRC requested changes
@timsb can the homepage button be styled like https://design-system.service.gov.uk 'Get started >' but switching their blue for our green.

Think the homepage should be clear that our patterns are supplemental. Maybe a new first line in the principles sections. Something like 'HMRC design resources supplements the [GOV.UK Design System](https://design-system.service.gov.uk). It follows the....'

I'll hold on comments on get started for now until you've changed the dir to /get-started/ and previewed it yourself (there's a few styling issues).

2024-08-01 16:09 UTC, Jon-Rowe-HMRC commented
In addition to the previous points...

'(Contractors/consultants)' > '(contractors/consultants)'?

'Mural' is the expectation for everyone to have an account? I thought Ops were still trying to restrict to people who really want it. I might be out of date. If not, remove from 'What you will need' as it's just guest access that anyone has?

'#team-design-system' add the link https://hmrcdigital.slack.com/archives/C014S77JCJW?name=C014S77JCJW#

'Service patterns also have a link to the team’s discussions on [GitHub](https://github.com/hmrc/design-patterns/issues).' > 'Service patterns also link to a [GitHub](https://github.com/hmrc/design-patterns/issues) discussion.'? (much of the discussion isn't the team)

'#gov uk-design-system' > '#govuk-design-system' and add link.

'HMRC’s preferred approach is to design using low-fidelity prototypes in the early stages of your project.' > 'HMRC’s preferred approach is to design using low-fidelity prototypes in early project stages.'

change any en dashes to em dashes

'The following tools are not authorised for use right now:' > 'The following tools are not authorised for use by service teams:'? Right now feels like false promise, and Figma/Sketch were authorised for the app team.

'"class=' > '" class=' (lots of these on what's new, do a mass search and replace)

Overall, looks really good. Lots of positive changes and helpful new content.

2024-08-21 09:53 UTC, JackHMRC commented
Hi @Jon-Rowe-HMRC 

I think I've covered all your points apart from the "'"class=' > '" class='" issue you raised. Tbh, I'm not sure what the issue is with this one, could you expand a bit on what needs doing please?

Cheers

Jack

2024-08-21 10:23 UTC, Jon-Rowe-HMRC commented
> Hi @Jon-Rowe-HMRC
> 
> I think I've covered all your points apart from the "'"class=' > '" class='" issue you raised. Tbh, I'm not sure what the issue is with this one, could you expand a bit on what needs doing please?
> 
> Cheers
> 
> Jack

It's missing spaces before 'class'. For example:
<a href="https://www.gov.uk/guidance/government-design-principles"class="govuk-link">

Should be:
<a href="https://www.gov.uk/guidance/government-design-principles" class="govuk-link">

2024-08-28 12:33 UTC, JackHMRC commented
Cheers Jon. These changes have been made.

2024-08-28 12:58 UTC, Jon-Rowe-HMRC approved these changes

2024-08-28 13:00 UTC, Jon-Rowe-HMRC commented
Not stopping publishing but on...
'HMRC design resources supplement GOV.UK Design System.'
The full stop shouldn't be part of the link. Should there be a 'the' before GOV.UK?  Feel free to ignore if you disagree :)

2024-08-29 09:54 UTC, Jon-Rowe-HMRC commented
'#gov uk-prototype-kit' > '#govuk-prototype-kit'

There's still some links with no space before the class eg '"class' should be '" class'

2024-08-29 14:33 UTC, Jon-Rowe-HMRC approved these changes

2024-08-30 08:44 UTC, Jon-Rowe-HMRC commented
'automatic prototype creation tool' has been changed to all straight quotes, but they should be curled

2024-08-30 10:39 UTC, timsb requested changes

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +All designs for HMRC services must follow <a href="https://www.gov.uk/guidance/government-design-principles" class="govuk-link">GOV.UK principles</a> and use <a href="https://design.tax.service.gov.u
The links 'HMRC' & 'GOV.UK' don't go to where you'd expect them to out of context. Could you change them to be something like 'HMRC design patterns' & 'GOV.UK design principles'?

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +For wider government patterns and components, the GOV.UK Design System Team is available on cross-government Slack at <a href="https://hmrcdigital.slack.com/archives/C014S77JCJW?name=C014S77JCJW#">#t
Not sure this is the correct link for the cross GOV slack channel?

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +For wider government patterns and components, the GOV.UK Design System Team is available on cross-government Slack at <a href="https://hmrcdigital.slack.com/archives/C014S77JCJW?name=C014S77JCJW#">#t
Doesn't make sense out of context. Could you include more of the copy to be part of the link e.g. 'cross-government Slack at #team-design-system'?

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +Designers can get support with HMRC-specific patterns from the HMRC Design Resources team on HMRC Slack at <a href="https://hmrcdigital.slack.com/archives/C014S77JCJW?name=C014S77JCJW#" class="govuk-
These links don't make sense out of context. Could you change them to something like 'HMRC Slack at #team-design-system' & 'HMRC Github issues'?

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +Designers can use low-fidelity prototypes to explore ideas quickly and cheaply before creating ‘high-fidelity’ prototypes that look more like the final product. Low-fidelity prototypes should be used
There's a mixture of cases 'Low-fidelity' & 'low-fidelity'. Is on of them correct or are they both correct depending on how you're using them?

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +<h3 class="govuk-heading-s" id="sketches">
I think this should be an `h4`

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +<h3 class="govuk-heading-s" id="google-suite">
I think this should be an `h4`

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +<h3 class="govuk-heading-s" id="mural">
I think this should be an `h4`

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +Full licences may not be available for every designer, please speak to the design leadership in your programme or P&UCD Ops to find out what is available for you.
```suggestion
Full licences may not be available for every designer, please speak to the design leadership in your programme or P&amp;UCD Ops to find out what is available for you.
```

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +    </p>
The `<p>` should close off before the `<ul>` starts

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> + High-fidelity prototypes are detailed, coded prototypes that mimic the behaviour of ‘finished’ services. High-fidelity prototypes will help you to perform user testing and demonstrate the service to
For the second 'High-fidelity' should it be lower case?

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> + Inside HMRC you can reach out in our #community-prototype Slack channel or speak to members of HMRC’s Design Resources Team. Support is also available on the cross-government Slack in the #govuk-pro
We've linked to Slack channels above. Should we be doing the same for these ones?

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> + If you are working on a new service or a new prototype follow the guidance on <a href="https://confluence.tools.tax.service.gov.uk/display/PROT/Creating+a+new+prototype+repository/" class="govuk-lin
I don't think these links don't go where I'd expect them to go out of context. For '#community-prototype' could the link be expanded out to 'HMRC Slack #community-prototype'?

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> + Pattern Checker is an <a href="https://chromewebstore.google.com/detail/pattern-checker/amjjliajblignodfdjalnfkekkeflkph?hl=en-GB">automated pattern and accessibility checker</a> for government serv
Not everyone uses Chrome. Should we mentioned that this is a Chrome browser extension?

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +
Not a massive one but there's a number of blank lines at the end of this file. There should just be 1 blank line at the end of the file.

2024-08-30 10:39 UTC, timsb commented on src/hmrc-content-style-guide/index.njk
> +<a href="https://www.gov.uk/service-manual/design/writing-for-user-interfaces" class="govuk-link">writing for user interfaces.</a>
The full stop shouldn't be part of the link
```suggestion
<a href="https://www.gov.uk/service-manual/design/writing-for-user-interfaces" class="govuk-link">writing for user interfaces</a>.
```

2024-08-30 10:39 UTC, timsb commented on src/index.njk
> +              <a href=" hmrc-design-patterns/" class="app-card">
Although this works as the browser has worked out what you meant it should be:
```suggestion
              <a href="/hmrc-design-patterns/" class="app-card">
```

2024-08-30 10:39 UTC, timsb commented on src/index.njk
> +              <a href=" patterns-hmrc-govuk-team/" class="app-card">
Although this works as the browser has worked out what you meant it should be:
```suggestion
              <a href="/patterns-hmrc-govuk-team/" class="app-card">
```

2024-08-30 10:39 UTC, timsb commented on src/index.njk
> +              <a href=" hmrc-content-style-guide/" class="app-card">
Although this works as the browser has worked out what you meant it should be:
```suggestion
              <a href="/hmrc-content-style-guide/" class="app-card">
```

2024-08-30 10:39 UTC, timsb commented on src/index.njk
> +           <p class="govuk-body">
Looks like you've got an opening paragraph element where there shouldn't be one. Should be remove
```suggestion
```

2024-08-30 10:39 UTC, timsb commented on src/index.njk
> +      <p class="govuk-body"> HMRC design resources supplement <a href="https://design-system.service.gov.uk/">GOV.UK Design System.</a> It follows the GOV.UK <a href="https://www.gov.uk/guidance/gove
There's a full stop in a link. Should be after:
```suggestion
      <p class="govuk-body"> HMRC design resources supplement <a href="https://design-system.service.gov.uk/">GOV.UK Design System</a>. It follows the GOV.UK <a href="https://www.gov.uk/guidance/government-design-principles" class="govuk-link">Government Design Principles</a>, <a href="https://www.gov.uk/service-manual/service-standard" class="govuk-link">Service Standard</a> and <a href="https://www.gov.uk/guidance/content-design" class="govuk-link">content design guidance</a>. HMRC also follows the GOV.UK <a href="https://design-system.service.gov.uk/accessibility/accessibility-strategy/" class="govuk-link">accessibility strategy</a> to improve the accessibility of our services.
```

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> +For wider government patterns and components, the GOV.UK Design System Team is available on cross-government Slack at <a href="https://hmrcdigital.slack.com/archives/C014S77JCJW?name=C014S77JCJW#">#t
Link needs `class='govuk-link'` added.

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> + You can <a href="https://design-system.service.gov.uk/get-started/prototyping/">follow instructions</a> in the GOV.UK Design System to get the kit running on your unmanaged device.
Link needs `class='govuk-link`.

2024-08-30 10:39 UTC, timsb commented on src/get-started/index.njk
> + Pattern Checker is an <a href="https://chromewebstore.google.com/detail/pattern-checker/amjjliajblignodfdjalnfkekkeflkph?hl=en-GB">automated pattern and accessibility checker</a> for government serv
Link needs `class='govuk-link'`.

2024-08-30 10:39 UTC, timsb commented on application/templates/partials/homepageBanner.njk
> +  href: "http://localhost:3000/Get-started/",
```suggestion
  href: "http://localhost:3000/get-started/",
```

2024-08-30 11:24 UTC, timsb commented on application/templates/partials/homepageBanner.njk
> +  href: "http://localhost:3000/get-started/",
```suggestion
  href: "/get-started/",
```

2024-08-30 11:30 UTC, timsb commented on src/get-started/index.njk
> +
```suggestion
  </p>
```

2024-08-30 11:30 UTC, timsb commented on src/get-started/index.njk
> +    </p>
```suggestion
```

2024-08-30 11:33 UTC, timsb approved these changes

2024-08-30 11:36 UTC, merged