Forms in a detailed guide - content edits
hmrc/design-system pull request #921
Opened 2024-10-31 11:39 UTC by JackHMRC

Hi John, 

Can you look over this and see that it is published while I'm on leave please?

Cheers

Jack

2024-11-11 09:47 UTC, timsb requested changes

2024-11-11 09:47 UTC, timsb commented on src/patterns-hmrc-govuk-team/forms-detailed-guide/index.njk
> +<li>Online services — These are built by service teams on the tax platform behind the Government Gateway, accessed with a green button with a URL, starting with https://www.taxservices.gov.uk/</li>
I've never seen `https://www.taxservices.gov.uk/` so I'm guessing it should actually be:
```suggestion
<li>Online services — These are built by service teams on the tax platform behind the Government Gateway, accessed with a green button with a URL, starting with https://www.tax.service.gov.uk/</li>
```

2024-11-11 09:47 UTC, timsb commented on src/patterns-hmrc-govuk-team/forms-detailed-guide/index.njk
> +  <li><a href="/guidance/register-as-a-bingo-promoter" class="govuk-link">Register as a bingo promoter</a> - an example of an online service with a green button and LC form to register by print and p
`/guidance/register-as-a-bingo-promoter` which resolves to https://www.tax.service.gov.uk/guidance/register-as-a-bingo-promoter` doesn't exist guessing this should be `gov.uk`?
```suggestion
  <li><a href="https://www.gov.uk/guidance/register-as-a-bingo-promoter" class="govuk-link">Register as a bingo promoter</a> - an example of an online service with a green button and LC form to register by print and post</li>
```

2024-11-11 09:47 UTC, timsb commented on src/patterns-hmrc-govuk-team/forms-detailed-guide/index.njk
> +  <li><a href="/guidance/claim-a-tax-refund-if-youve-stopped-work-and-flexibly-accessed-all-of-your-pension-p50z" class="govuk-link">Claim a tax refund if you've stopped work and flexibly accessed al
As previous comment. Guessing this should be:
```suggestion
  <li><a href="https://www.gov.uk/guidance/claim-a-tax-refund-if-youve-stopped-work-and-flexibly-accessed-all-of-your-pension-p50z" class="govuk-link">Claim a tax refund if you've stopped work and flexibly accessed all of your pension (P50Z)</a> —  example of a service with a green button and both an interactive guidance (print and post) form and a PDF (print and post) form for digitally excluded users</li>
```

2024-11-11 09:47 UTC, timsb commented on src/patterns-hmrc-govuk-team/forms-detailed-guide/index.njk
> +  IG tools with form options must follow this pattern and other GOV.UK patterns for form choices — unless evidence of a strong user need demonstrates a reason not to.^
Guessing the caret (^) shouldn't be at the end of this sentence?
```suggestion
  IG tools with form options must follow this pattern and other GOV.UK patterns for form choices — unless evidence of a strong user need demonstrates a reason not to.
```

2024-11-11 09:47 UTC, timsb commented on src/patterns-hmrc-govuk-team/forms-detailed-guide/index.njk
> +  </p>
The `h3` shouldn't be wrapped in a paragraph.
```suggestion
  <h3 class="govuk-heading-s" id="formats">Example</h3> 
```

2024-11-11 09:47 UTC, timsb commented on src/patterns-hmrc-govuk-team/forms-detailed-guide/index.njk
> +      </p>
The `h3` shouldn't be wrapped in a paragraph.
```suggestion
      <h3 class="govuk-heading-s" id="formats">Example</h3> 
```

2024-11-19 09:50 UTC, Jon-Rowe-HMRC approved these changes

2024-11-19 09:51 UTC, Edem-Ag approved these changes

2024-11-19 09:55 UTC, timsb approved these changes

2024-11-19 09:59 UTC, merged